-- Add ESG indicators for SASB (Sustainability Accounting Standards Board)
INSERT INTO public.esg_indicators (framework_id, indicator_code, name, category, subcategory, description, unit_of_measurement, reporting_frequency, is_quantitative, materiality_level)
SELECT 
  (SELECT id FROM public.esg_frameworks WHERE name = 'Sustainability Accounting Standards Board'),
  code, name, category, subcategory, description, unit_of_measurement, reporting_frequency, is_quantitative, materiality_level
FROM (VALUES
  ('SASB-ENV-1', 'GHG Emissions - Scope 1', 'environmental', 'climate', 'Direct greenhouse gas emissions from owned or controlled sources', 'metric tons CO2e', 'annual', true, 'high'),
  ('SASB-ENV-2', 'GHG Emissions - Scope 2', 'environmental', 'climate', 'Indirect greenhouse gas emissions from purchased energy', 'metric tons CO2e', 'annual', true, 'high'),
  ('SASB-ENV-3', 'GHG Emissions - Scope 3', 'environmental', 'climate', 'All other indirect greenhouse gas emissions in value chain', 'metric tons CO2e', 'annual', true, 'medium'),
  ('SASB-ENV-4', 'Energy Consumption', 'environmental', 'energy', 'Total energy consumed from all sources', 'GJ', 'annual', true, 'high'),
  ('SASB-ENV-5', 'Renewable Energy Percentage', 'environmental', 'energy', 'Percentage of energy from renewable sources', '%', 'annual', true, 'medium'),
  ('SASB-ENV-6', 'Water Withdrawal', 'environmental', 'water', 'Total water withdrawn from all sources', 'm³', 'annual', true, 'high'),
  ('SASB-ENV-7', 'Water Discharge Quality', 'environmental', 'water', 'Quality of water discharged back to environment', 'text', 'annual', false, 'medium'),
  ('SASB-ENV-8', 'Waste Generated', 'environmental', 'waste', 'Total waste generated by organization', 'metric tons', 'annual', true, 'high'),
  ('SASB-ENV-9', 'Waste Diverted from Disposal', 'environmental', 'waste', 'Waste diverted through recycling, reuse, or recovery', 'metric tons', 'annual', true, 'medium'),
  ('SASB-ENV-10', 'Hazardous Waste', 'environmental', 'waste', 'Hazardous waste generated and disposed', 'metric tons', 'annual', true, 'high'),
  ('SASB-SOC-1', 'Employee Health & Safety Incidents', 'social', 'workforce', 'Total recordable incident rate (TRIR)', 'rate per 200,000 hours', 'annual', true, 'high'),
  ('SASB-SOC-2', 'Lost Time Injury Frequency Rate', 'social', 'workforce', 'Frequency of lost time injuries per million hours worked', 'rate per million hours', 'annual', true, 'high'),
  ('SASB-SOC-3', 'Employee Training Hours', 'social', 'workforce', 'Average training hours per employee', 'hours', 'annual', true, 'medium'),
  ('SASB-SOC-4', 'Employee Turnover Rate', 'social', 'workforce', 'Percentage of employees who left the organization', '%', 'annual', true, 'medium'),
  ('SASB-SOC-5', 'Gender Pay Gap', 'social', 'diversity', 'Difference in pay between male and female employees', '%', 'annual', true, 'medium'),
  ('SASB-SOC-6', 'Board Diversity', 'social', 'diversity', 'Diversity of board members by gender, age, ethnicity', '%', 'annual', true, 'medium'),
  ('SASB-SOC-7', 'Supply Chain Labor Standards', 'social', 'human rights', 'Compliance with labor standards in supply chain', 'text', 'annual', false, 'high'),
  ('SASB-SOC-8', 'Community Investment', 'social', 'community', 'Total value of community programs and charitable giving', 'currency', 'annual', true, 'medium'),
  ('SASB-GOV-1', 'Anti-Corruption Training', 'governance', 'ethics', 'Percentage of employees trained in anti-corruption policies', '%', 'annual', true, 'high'),
  ('SASB-GOV-2', 'Business Ethics Violations', 'governance', 'ethics', 'Number of confirmed incidents of corruption and bribery', 'count', 'annual', true, 'high'),
  ('SASB-GOV-3', 'Data Privacy Breaches', 'governance', 'privacy', 'Number of substantiated complaints regarding breaches of customer privacy', 'count', 'annual', true, 'high'),
  ('SASB-GOV-4', 'Customer Data Protection', 'governance', 'privacy', 'Measures taken to protect customer data and privacy', 'text', 'annual', false, 'high'),
  ('SASB-GOV-5', 'Product Quality Incidents', 'governance', 'quality', 'Number of incidents of non-compliance with product quality standards', 'count', 'annual', true, 'medium'),
  ('SASB-GOV-6', 'Supplier Sustainability Assessment', 'governance', 'supply chain', 'Percentage of suppliers assessed for sustainability criteria', '%', 'annual', true, 'medium')
) AS t(code, name, category, subcategory, description, unit_of_measurement, reporting_frequency, is_quantitative, materiality_level);

-- Add ESG indicators for TCFD (Task Force on Climate-related Financial Disclosures)
INSERT INTO public.esg_indicators (framework_id, indicator_code, name, category, subcategory, description, unit_of_measurement, reporting_frequency, is_quantitative, materiality_level)
SELECT 
  (SELECT id FROM public.esg_frameworks WHERE name = 'Task Force on Climate-related Financial Disclosures'),
  code, name, category, subcategory, description, unit_of_measurement, reporting_frequency, is_quantitative, materiality_level
FROM (VALUES
  ('TCFD-GOV-1', 'Board Oversight of Climate Risks', 'governance', 'oversight', 'Description of board oversight of climate-related risks and opportunities', 'text', 'annual', false, 'high'),
  ('TCFD-GOV-2', 'Management Role in Climate Assessment', 'governance', 'management', 'Description of management role in assessing and managing climate risks', 'text', 'annual', false, 'high'),
  ('TCFD-STRAT-1', 'Climate Risk Impact on Strategy', 'environmental', 'strategy', 'Climate-related risks and opportunities impact on business, strategy, and financial planning', 'text', 'annual', false, 'high'),
  ('TCFD-STRAT-2', 'Climate Scenario Analysis', 'environmental', 'strategy', 'Resilience of strategy under different climate scenarios (2°C or lower)', 'text', 'annual', false, 'high'),
  ('TCFD-STRAT-3', 'Physical Climate Risks', 'environmental', 'risk', 'Physical risks from climate change (acute and chronic)', 'text', 'annual', false, 'high'),
  ('TCFD-STRAT-4', 'Transition Climate Risks', 'environmental', 'risk', 'Transition risks from moving to lower-carbon economy', 'text', 'annual', false, 'high'),
  ('TCFD-STRAT-5', 'Climate Opportunities', 'environmental', 'opportunity', 'Climate-related opportunities identified by the organization', 'text', 'annual', false, 'medium'),
  ('TCFD-RISK-1', 'Climate Risk Management Process', 'governance', 'risk management', 'Processes for identifying and assessing climate-related risks', 'text', 'annual', false, 'high'),
  ('TCFD-RISK-2', 'Climate Risk Integration', 'governance', 'risk management', 'How climate risk processes are integrated into overall risk management', 'text', 'annual', false, 'high'),
  ('TCFD-METR-1', 'GHG Emissions Scope 1 & 2', 'environmental', 'metrics', 'Direct and indirect GHG emissions (Scope 1 and 2)', 'metric tons CO2e', 'annual', true, 'high'),
  ('TCFD-METR-2', 'GHG Emissions Scope 3', 'environmental', 'metrics', 'Value chain GHG emissions (Scope 3) if appropriate', 'metric tons CO2e', 'annual', true, 'medium'),
  ('TCFD-METR-3', 'Climate-Related Targets', 'environmental', 'targets', 'Targets used to manage climate-related risks and opportunities', 'text', 'annual', false, 'high'),
  ('TCFD-METR-4', 'Performance Against Targets', 'environmental', 'performance', 'Performance against climate-related targets', 'text', 'annual', false, 'high'),
  ('TCFD-METR-5', 'Carbon Pricing', 'environmental', 'metrics', 'Internal carbon price used in decision-making', 'currency per ton CO2e', 'annual', true, 'medium'),
  ('TCFD-METR-6', 'Climate-Related Financial Impact', 'environmental', 'financial', 'Financial impact of climate-related risks and opportunities', 'currency', 'annual', true, 'high')
) AS t(code, name, category, subcategory, description, unit_of_measurement, reporting_frequency, is_quantitative, materiality_level);

-- Add ESG indicators for UN SDGs (Sustainable Development Goals)
INSERT INTO public.esg_indicators (framework_id, indicator_code, name, category, subcategory, description, unit_of_measurement, reporting_frequency, is_quantitative, materiality_level)
SELECT 
  (SELECT id FROM public.esg_frameworks WHERE name = 'UN Sustainable Development Goals'),
  code, name, category, subcategory, description, unit_of_measurement, reporting_frequency, is_quantitative, materiality_level
FROM (VALUES
  ('SDG-1', 'SDG 1: No Poverty', 'social', 'poverty', 'Contribution to ending poverty in all its forms everywhere', 'text', 'annual', false, 'medium'),
  ('SDG-2', 'SDG 2: Zero Hunger', 'social', 'hunger', 'Contribution to ending hunger, achieving food security and improved nutrition', 'text', 'annual', false, 'medium'),
  ('SDG-3', 'SDG 3: Good Health and Well-being', 'social', 'health', 'Contribution to ensuring healthy lives and promoting well-being for all', 'text', 'annual', false, 'medium'),
  ('SDG-4', 'SDG 4: Quality Education', 'social', 'education', 'Contribution to ensuring inclusive and equitable quality education', 'text', 'annual', false, 'medium'),
  ('SDG-5', 'SDG 5: Gender Equality', 'social', 'gender', 'Contribution to achieving gender equality and empowering all women and girls', 'text', 'annual', false, 'medium'),
  ('SDG-6', 'SDG 6: Clean Water and Sanitation', 'environmental', 'water', 'Contribution to ensuring availability and sustainable management of water', 'text', 'annual', false, 'medium'),
  ('SDG-7', 'SDG 7: Affordable and Clean Energy', 'environmental', 'energy', 'Contribution to ensuring access to affordable, reliable, sustainable energy', 'text', 'annual', false, 'medium'),
  ('SDG-8', 'SDG 8: Decent Work and Economic Growth', 'social', 'employment', 'Contribution to promoting sustained, inclusive economic growth and decent work', 'text', 'annual', false, 'medium'),
  ('SDG-9', 'SDG 9: Industry, Innovation and Infrastructure', 'governance', 'innovation', 'Contribution to building resilient infrastructure and fostering innovation', 'text', 'annual', false, 'medium'),
  ('SDG-10', 'SDG 10: Reduced Inequalities', 'social', 'inequality', 'Contribution to reducing inequality within and among countries', 'text', 'annual', false, 'medium'),
  ('SDG-11', 'SDG 11: Sustainable Cities and Communities', 'social', 'urban', 'Contribution to making cities and human settlements inclusive, safe, resilient', 'text', 'annual', false, 'medium'),
  ('SDG-12', 'SDG 12: Responsible Consumption and Production', 'environmental', 'consumption', 'Contribution to ensuring sustainable consumption and production patterns', 'text', 'annual', false, 'medium'),
  ('SDG-13', 'SDG 13: Climate Action', 'environmental', 'climate', 'Contribution to taking urgent action to combat climate change', 'text', 'annual', false, 'high'),
  ('SDG-14', 'SDG 14: Life Below Water', 'environmental', 'oceans', 'Contribution to conserving and sustainably using oceans, seas and marine resources', 'text', 'annual', false, 'medium'),
  ('SDG-15', 'SDG 15: Life on Land', 'environmental', 'biodiversity', 'Contribution to protecting, restoring and promoting sustainable use of terrestrial ecosystems', 'text', 'annual', false, 'medium'),
  ('SDG-16', 'SDG 16: Peace, Justice and Strong Institutions', 'governance', 'institutions', 'Contribution to promoting peaceful and inclusive societies and effective institutions', 'text', 'annual', false, 'medium'),
  ('SDG-17', 'SDG 17: Partnerships for the Goals', 'governance', 'partnerships', 'Contribution to strengthening partnerships for sustainable development', 'text', 'annual', false, 'medium')
) AS t(code, name, category, subcategory, description, unit_of_measurement, reporting_frequency, is_quantitative, materiality_level);