// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anuvztvypsihzlbkewci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFudXZ6dHZ5cHNpaHpsYmtld2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTc4ODUsImV4cCI6MjA2Mzk5Mzg4NX0.YA4ZwsRj9t-0YllEQA_NTZvrir3TJGtCb8raCsFn1k0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);